version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache: 
          keys: 
            - v0-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v0-dep-
      
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv 
            pipenv install -de .

      - save_cache:                  
          key: v0-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: pipenv run pytest            
          